feat: django 기본 설정
minesp3164/company_vacation_management pull request #7
Opened 2023-05-11 17:10 UTC by minesp3164

2023-05-11 17:16 UTC, galaxy4276 requested changes
리뷰 확인해주세요.

2023-05-11 17:16 UTC, galaxy4276 commented on backend_app/backend_app/__pycache__/__init__.cpython-310.pyc
연관 없는 캐시파일 삭제해주세요.

2023-05-11 17:16 UTC, galaxy4276 commented on backend_app/backend_app/__pycache__/wsgi.cpython-310.pyc
연관 없는 캐시파일 삭제해주세요.

2023-05-11 17:16 UTC, galaxy4276 requested changes
리뷰 확인해주세요.

2023-05-11 17:18 UTC, galaxy4276 requested changes
리뷰 확인하세요.

2023-05-11 17:18 UTC, galaxy4276 commented on backend_app/backend_app/settings.py
> +SECRET_KEY = 'django-insecure-l73(z@u+%n36!o9+k80$1t%ws2^b8=sy*6$qd25o1@+doc&@2('
```suggestion
SECRET_KEY = (외부 값으로 대체)
```

서버의 비밀 키는 절대 외부로 공유되면 안되요.
[environ](https://www.daleseo.com/python-os-environ/) 같은 환경변수 라이브러리를 사용해서 외부에서 가져올 수 있게 수정하세요.

2023-05-16 02:47 UTC, galaxy4276 requested changes
코드 리뷰 확인 바랍니다.

2023-05-16 02:47 UTC, galaxy4276 commented on backend_app/backend_app/settings.py
> +        'HOST': 'localhost',
이렇게 하드코딩해두면 외부에 시스템 운영을 위한 중요한 변수값을 노출하게 됩니다.
외부 환경변수 주입 코드로 대체바랍니다.

2023-05-16 09:03 UTC, minesp3164 commented
이대로 merge 하면 될까요?

2023-05-16 11:21 UTC, merged